name: Build and push Docker images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate config file
        run: cp -r ./config/hoshino/config_example ./config/hoshino/config

      - name: Prepare Environment
        run: |
          python3 -m pip install -r requirements.txt
          git submodule update --init --recursive
      
      - name: Build docker image
        run: |
          docker login --username=${{ secrets.DOCKER_USN }} --password=${{ secrets.DOCKER_PWD }}
          docker build -t maxesisn/tachibanabot:latest .
          docker push maxesisn/tachibanabot:latest
          
